
figure
plot((RESULTS.X_Loadings(:,1)), ...
    (RESULTS.X_Loadings(:,2)), '*')
text((RESULTS.X_Loadings(:,1)),...
    (RESULTS.X_Loadings(:,2)), ...
    X_TABLE.Properties.VariableNames)
hold on
plot((RESULTS.Y_Loadings(:,1)), ...
    (RESULTS.Y_Loadings(:,2)), 'o',...
    'MarkerFaceColor', 'blue')
text((RESULTS.Y_Loadings(:,1)),...
    (RESULTS.Y_Loadings(:,2)), ...
    Y_TABLE.Properties.VariableNames)

title('X- and Y-loadings on the first two PLS components');
xlabel('PLS-1');
ylabel('PLS-2');