plot(scaledata(PLS_Oil.X_Loadings(:,1),-1,1), ...
    scaledata(PLS_Oil.X_Loadings(:,2),-1,1), '*')
text(scaledata(PLS_Oil.X_Loadings(:,1),-1,1),...
    scaledata(PLS_Oil.X_Loadings(:,2),-1,1), ...
    ChemicalData.Properties.VariableNames)
hold on
plot(scaledata(PLS_Oil.Y_Loadings(1,:),-1,1), ...
    scaledata(PLS_Oil.Y_Loadings(2,:),-1,1), 'o')
 text(scaledata(PLS_Oil.Y_Loadings(1,:),-1,1), ...
     scaledata(PLS_Oil.Y_Loadings(2,:),-1,1), ...
     SensoryData.Properties.VariableNames)
axis([-1.2,1.2,-1.2,1.2])

figure
plot(PLS_Oil.X_Scores(:,1), PLS_Oil.Y_Scores(:,1), '*')

