function pls_FRfigures(RESULTS, X_TABLE, Y_TABLE)
figure
plot((RESULTS.X_Loadings(:,1)), ...
    (RESULTS.X_Loadings(:,2)), 'o',...
    'MarkerFaceColor', 'blue',...
    'MarkerEdgeColor', 'blue')
text((RESULTS.X_Loadings(:,1))+0.02,...
    (RESULTS.X_Loadings(:,2))+0.02, ...
    X_TABLE.Properties.VariableNames,...
    'HorizontalAlignment','left')
hold on
plot((RESULTS.Y_Loadings(:,1)), ...
    (RESULTS.Y_Loadings(:,2)), 'v',...
    'MarkerFaceColor', 'black', ...
    'MarkerEdgeColor', 'black')
text((RESULTS.Y_Loadings(:,1))+0.02,...
    (RESULTS.Y_Loadings(:,2))+0.02, ...
    Y_TABLE.Properties.VariableNames,...
    'HorizontalAlignment','left')

title('X- and Y-loadings on the first two PLS components');
xlabel('PLS-1');
ylabel('PLS-2');

figure
plot(scaledata(RESULTS.X_Scores(:,1),-1,1), ...
    scaledata(RESULTS.X_Scores(:,2),-1,1), 'o',...
    'MarkerFaceColor', 'blue',...
    'MarkerEdgeColor', 'blue')
text(scaledata(RESULTS.X_Scores(:,1),-1,1)+0.02,...
    scaledata(RESULTS.X_Scores(:,2),-1,1)+0.02, ...
    X_TABLE.Properties.RowNames,...
    'HorizontalAlignment','left')
hold on
plot(scaledata(RESULTS.Y_Loadings(:,1),-1,1), ...
    scaledata(RESULTS.Y_Loadings(:,2),-1,1), 'v',...
    'MarkerFaceColor', 'black', ...
    'MarkerEdgeColor', 'black')
text(scaledata(RESULTS.Y_Loadings(:,1),-1,1)+0.02,...
    scaledata(RESULTS.Y_Loadings(:,2),-1,1)+0.02, ...
    Y_TABLE.Properties.VariableNames,...
    'HorizontalAlignment','left')

title('BIPLOT of the first two PLS components');
xlabel('PLS-1');
ylabel('PLS-2');
axis([-1.2,1.2,-1.2,1.2]);